image: docker:stable

stages:
    - docker
    - build
    - deploy

variables:
    CACHE_DIR: "build/cache"
    DOCKER_IMAGE: "gitlab_${CI_PROJECT_NAME}_${CI_PIPELINE_ID}"

cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
        - $CACHE_DIR/
    policy: pull

services:
    - docker:stable-dind

before_script:
    - echo -e "\e[1;97;44m > Building docker image... \e[0m"
    - |
        if [[ -f "$CACHE_DIR/docker.tar" ]]; then
            docker load -i "$CACHE_DIR/docker.tar"
        fi
    - docker build -t "$DOCKER_IMAGE" --pull .


docker:
    stage: docker
    cache:
        key: "$CI_COMMIT_REF_NAME"
        paths:
            - $CACHE_DIR/
        policy: pull-push
    script:
        - echo -e "\e[1;97;44m > Saving docker image... \e[0m"
        - mkdir -p "$CACHE_DIR"
        - docker save -o "$CACHE_DIR/docker.tar" $(docker images -q)
        - |
            docker run --rm "$DOCKER_IMAGE" /bin/bash -l -c '
                echo -e "\e[1;97;44m > Dumping system packages... \e[0m"
                pacman --color=always -Q
                echo -e "\e[1;97;44m > Dumping vcpkg packages... \e[0m"
                vcpkg list
            '


build:
    stage: build
    script: |
        docker run --rm "$DOCKER_IMAGE" /bin/bash -l -c '
            echo -e "\n\e[1;97;44m > Building... \e[0m"
            export CXXFLAGS="-fdiagnostics-color=always -isystem /opt/vcpkg/installed/x64-linux/include -L /opt/vcpkg/installed/x64-linux/lib"
            export CLICOLOR_FORCE="1"
            mkdir -p "build/debug"
            cd "build/debug"
            cmake "-DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_BUILD_TYPE=Debug" "../.."
            make -j$(nproc) -Orecurse
            mkdir "../release"
            cd "../release"
            cmake "-DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_BUILD_TYPE=RelWithDebInfo" "../.."
            make -j$(nproc) -Orecurse
        '

misc:
    stage: build
    script: |
        docker run --rm "$DOCKER_IMAGE" /bin/bash -l -c '
            echo -e "\e[1;97;44m > Formatting with clang-format... \e[0m"
            err=0
            for f in **/*.h **/*.cpp **/*.inl; do
                diff=$(clang-format "$f" | diff -d --color=always "$f" -)
                if [[ ! -z "$diff" ]]; then
                    echo -e "\e[1m$f\e[0m"
                    echo "$diff"
                    echo
                    ((++err))
                fi
            done
            if [[ $err -eq 0 ]]; then
                echo -e "\e[1mEverything is already formatted!\e[0m"
            fi
            exit $err
        '


pages:
    stage: deploy
    script: |
        docker run --rm --mount type=bind,source="public",target="/mnt/public" "$DOCKER_IMAGE" /bin/bash -l -c '
            export CI_COMMIT_REF_SLUG=develop

            mkdir -p "build/doc"
            doxygen
            mkdir "/mnt/public/doc"
            mv "build/doc/html" "/mnt/public/doc/$CI_COMMIT_REF_SLUG"
        '
    artifacts:
        paths:
            - public
    #only:
    #    - master
    #    - develop
